// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDocKN_ESFMv-rue4Aj9GtaWJQHdC-aWpE',
    appId: '1:501499969376:web:2c08019e420679d89fa805',
    messagingSenderId: '501499969376',
    projectId: 'my-fire-cli',
    authDomain: 'my-fire-cli.firebaseapp.com',
    storageBucket: 'my-fire-cli.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHuuPJ9rBewvuJEctEJ_Fi4Oy6jGYwYxA',
    appId: '1:501499969376:android:6d8154557156a3659fa805',
    messagingSenderId: '501499969376',
    projectId: 'my-fire-cli',
    storageBucket: 'my-fire-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC40ZjHme_cP583y4D01pio2pKn5YDA0Y8',
    appId: '1:501499969376:ios:dffb64a97d69d4299fa805',
    messagingSenderId: '501499969376',
    projectId: 'my-fire-cli',
    storageBucket: 'my-fire-cli.appspot.com',
    iosBundleId: 'com.example.firebasecli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC40ZjHme_cP583y4D01pio2pKn5YDA0Y8',
    appId: '1:501499969376:ios:bb11c14490d065639fa805',
    messagingSenderId: '501499969376',
    projectId: 'my-fire-cli',
    storageBucket: 'my-fire-cli.appspot.com',
    iosBundleId: 'com.example.firebasecli.RunnerTests',
  );
}
